/****************************************************************************
 * boards/p2/p2x8c4m64p/p2-ec32mb/include/board_flash_layout.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/* Generated by tools/p2/generate-flash-layout.py. */

#ifndef __BOARDS_P2_P2X8C4M64P_P2_EC32MB_INCLUDE_FLASH_LAYOUT_H
#define __BOARDS_P2_P2X8C4M64P_P2_EC32MB_INCLUDE_FLASH_LAYOUT_H

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

#define P2_FLASH_SIZE_BYTES       0x01000000u
#define P2_FLASH_PAGE_BYTES       0x00000100u
#define P2_FLASH_ERASE_BYTES      0x00001000u
#define P2_FLASH_LARGE_ERASE_BYTES 0x00010000u
#define P2_FLASH_ROM_BOOT_WINDOW_BYTES 0x00000400u
#define P2_FLASH_PAYLOAD_OFFSET   0x00000090u
#define P2_FLASH_MIN_PROGRAM_PAGES 0x00000004u
#define P2_FLASH_BOOT_IMAGE_MAX   0x0007c000u
#define P2_FLASH_MAX_PROGRAM_END  0x0007c100u
#define P2_FLASH_BOOT_OFFSET      0x00000000u
#define P2_FLASH_BOOT_SIZE        0x00080000u
#define P2_FLASH_FS_OFFSET        0x00080000u
#define P2_FLASH_FS_SIZE          0x00f80000u

#endif
