/* SPDX-License-Identifier: Apache-2.0 */

#include "abi_probe.h"

#define FIXED_REGISTER_PROBE(number) \
  P2_NOINLINE p2_u32 p2_probe_fixed_r##number(p2_u32 value) \
  { \
    register p2_u32 fixed __asm__("r" #number) = value; \
    __asm__ volatile ("" : "+r" (fixed)); \
    return fixed; \
  }

FIXED_REGISTER_PROBE(0)
FIXED_REGISTER_PROBE(1)
FIXED_REGISTER_PROBE(2)
FIXED_REGISTER_PROBE(3)
FIXED_REGISTER_PROBE(4)
FIXED_REGISTER_PROBE(5)
FIXED_REGISTER_PROBE(6)
FIXED_REGISTER_PROBE(7)
FIXED_REGISTER_PROBE(8)
FIXED_REGISTER_PROBE(9)
FIXED_REGISTER_PROBE(10)
FIXED_REGISTER_PROBE(11)
FIXED_REGISTER_PROBE(12)
FIXED_REGISTER_PROBE(13)
FIXED_REGISTER_PROBE(14)
FIXED_REGISTER_PROBE(15)
FIXED_REGISTER_PROBE(16)
FIXED_REGISTER_PROBE(17)
FIXED_REGISTER_PROBE(18)
FIXED_REGISTER_PROBE(19)
FIXED_REGISTER_PROBE(20)
FIXED_REGISTER_PROBE(21)
FIXED_REGISTER_PROBE(22)
FIXED_REGISTER_PROBE(23)
FIXED_REGISTER_PROBE(24)
FIXED_REGISTER_PROBE(25)
FIXED_REGISTER_PROBE(26)
FIXED_REGISTER_PROBE(27)
FIXED_REGISTER_PROBE(28)
FIXED_REGISTER_PROBE(29)
FIXED_REGISTER_PROBE(30)
FIXED_REGISTER_PROBE(31)
